---
title: "ggseg tstats"
author: "Julia"
date: "2025-07-24"
output: html_document
---

```{r}
library(tidyverse)
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(caret)
library(ranger)
library(ggseg)
library(broom)
```
## Load data
```{r}
lh_aparc_thickness <- read_tsv("/projects/svaillancourt/PEPP_traj/data/raw/freesurfer_measurements/lh.aparc.thickness.tsv")
classes <- read.csv("/projects/aqian/PEPP_traj/reports/GMM_class_membership/gmm_class_div_18mo.csv")
rh_aparc_thickness <- read_tsv("/projects/svaillancourt/PEPP_traj/data/raw/freesurfer_measurements/rh.aparc.thickness.tsv")
subj <- read.csv("/projects/svaillancourt/pin_sub_table.csv")
lh_aparc_thickness <- lh_aparc_thickness %>%
    rename(FEP_ID = lh.aparc.thickness)
rh_aparc_thickness <- rh_aparc_thickness %>%
    rename(FEP_ID = rh.aparc.thickness)
aparc_thickness <- left_join(lh_aparc_thickness, rh_aparc_thickness, by = "FEP_ID")
classes <- classes %>%
  select(pin, class_sans_2)
joined <- left_join(subj, classes, by="pin")
aparc_thickness <- left_join(joined, aparc_thickness, by = "FEP_ID")
aparc_thickness <- aparc_thickness %>%
    mutate(class = case_when(
        class_sans_2 == 1 ~ "Persistent_High",
        TRUE ~ "Persistent_Low"
    ))
```

```{r}
Persistent_high <- aparc_thickness %>%
  filter(class == "Persistent_High")
Persistent_low <- aparc_thickness %>%
  filter(class == "Persistent_Low")
```

```{r}
# Initialize a dataframe to store the t-values and ROI names
effect_size <- data.frame(label = character(), tstat = numeric(), stringsAsFactors = FALSE)
# Loop through each column starting from the 4th column
for (i in 4:74) {
  # Get the ROI name
  roi_name <- colnames(Persistent_low)[i]
  # Perform a t-test between the ith column of each dataframe
  t <- t.test(Persistent_low[[i]], Persistent_high [[i]])
  # Extract the t-value
  tstat_value <- t$statistic
  # Append the ROI name and t-statistic to the dataframe
  effect_size <- rbind(effect_size, data.frame(label = roi_name, tstat = tstat_value))
}
ct_effect_size <- effect_size
ct_effect_size$label <- sub("_area","", ct_effect_size$label)
```

```{r}
library(ggseg)
ggseg(atlas = dk,
      .data = ct_effect_size,
      color = "black",
      mapping = aes(fill = tstat_value),
      position = "stacked") + theme_void() + scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0, lim = c(-3,3))
```
```{r}
### t-test statistics for cortical thickness
t_lh_rostralanteriorcingulate <- t.test(Persistent_low$lh_rostralanteriorcingulate, Persistent_high$lh_rostralanteriorcingulate) 
p.adjust(t_lh_rostralanteriorcingulate$p.value, method = "holm", n = 78)
## ^t = -3.5652, df = 84.131, p-value = 0.0006025; adjusted p-value = 0.047

t_lh_posteriorcingulate <- t.test(Persistent_low$lh_posteriorcingulate, Persistent_high$lh_posteriorcingulate)
p.adjust(t_lh_posteriorcingulate$p.value, method = "holm", n = 78)
## ^t = -3.0492, df = 67.807, p-value = 0.003271
t.test(Persistent_low$lh_frontalpole, Persistent_high$lh_frontalpole)
## ^t = -2.4461, df = 64.38, p-value = 0.01719
t.test(Persistent_low$lh_lingual, Persistent_high$lh_lingual)
## ^t = -2.4421, df = 77.986, p-value = 0.01686
t.test(Persistent_low$rh_medialorbitofrontal, Persistent_high$rh_medialorbitofrontal)
## ^t = -2.1805, df = 78.782, p-value = 0.0322
t.test(Persistent_low$lh_precuneus, Persistent_high$lh_precuneus)
## ^t = -2.1267, df = 71.923, p-value = 0.03687
t.test(Persistent_low$rh_cuneus, Persistent_high$rh_cuneus)
## ^t = -2.1039, df = 71.332, p-value = 0.03892
t.test(Persistent_low$rh_precuneus, Persistent_high$rh_precuneus)
## ^t = -2.0596, df = 60.599, p-value = 0.04374
t.test(Persistent_low$rh_lingual, Persistent_high$rh_lingual)
## ^t = -2.0231, df = 88.628, p-value = 0.04608
t.test(Persistent_low$rh_paracentral, Persistent_high$rh_paracentral)
## ^t = -1.9972, df = 69.534, p-value = 0.04972
t.test(Persistent_low$rh_frontalpole, Persistent_high$rh_frontalpole) ## not sig anymore

t.test(Persistent_low$rh_temporalpole, Persistent_high$rh_temporalpole) ## none of the positive t-stats was significant
```